name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: w9jds/firebase-action@v2.2.0
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: \${{ secrets.FIREBASE_TOKEN }}